<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE catalog [
<!ELEMENT catalog (title?, product+)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT product (ID, Name, specs, price, quantity, image)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT specs (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT images (#PCDATA)>
]>

<catalog>
  <title>Refrigerators of the week</title>
  <product>
     <ID>rf0032</ID>
     <Name>Estate</Name>
     <specs>Whites 14.4 Cu. Ft. top</specs>
     <price>500</price>
     <quantity>3</quantity>
     <image>http://ugweb.cs.ualberta.ca/~c410/W10/410/work/img/frige1.jpg</image>
  </product>
  <product>
     <ID>rf2334</ID>
     <Name>LG</Name>
     <specs>Stainless 19.7 Cu. Ft. bottom</specs>
     <price>1200</price>
     <quantity>1</quantity>
     <image>http://ugweb.cs.ualberta.ca/~c410/W10/410/work/img/frige2.jpg</image>
  </product>
  <product>
     <ID>rf3299</ID>
     <Name>Samsung</Name>
     <specs>White 18 Cu. Ft. french door</specs>
     <price>1100</price>
     <quantity>2</quantity>
     <image>http://ugweb.cs.ualberta.ca/~c410/W10/410/work/img/frige3.jpg</image>
  </product>
  <product>
     <ID>rf1338</ID>
     <Name>Bosh</Name>
     <specs>Stainless 21.7 Cu. Ft. side-by-side</specs>
     <price>3200</price>
     <quantity>2</quantity>
     <image>http://ugweb.cs.ualberta.ca/~c410/W10/410/work/img/frige4.jpg</image>
  </product>
  <product>
     <ID>rf0038</ID>
     <Name>Whirlpool</Name>
     <specs>White 18.6 Cu. Ft. bottom</specs>
     <price>900</price>
     <quantity>5</quantity>
     <image>http://ugweb.cs.ualberta.ca/~c410/W10/410/work/img/frige5.jpg</image>
  </product>
</catalog>